<?
DEFINE('ALL_nameGAME', 'Time OF Wars');
DEFINE('YES', 'Да');
DEFINE('NO', 'Нет');
DEFINE('playerblocked', '<CENTER><b>Персонаж заблокирован</b><br /><i>Причина:</i> %s</CENTER>');
DEFINE('_refsystem', 'Реферальная система: ( %s )');
DEFINE('hplevel', 'Уровень жизни');
DEFINE('_MAIN_copy', 'копировать');
DEFINE('_a_href', '<A HREF="%s" %s>%s</A>');
DEFINE('_button_change', 'Изменить');
DEFINE('_button_add', 'Добавить');
DEFINE('_GOOUT', 'Вернуться');
DEFINE('_chaosERR', 'С проклятьем вход воспрещен<br><input type=button value="Вернуться" onClick="window.location.href=\'?goto=pl\'">');
DEFINE('_adminerr', 'Вы не являетесь администратором.');


DEFINE('_ADM_m', 'молчанка');
DEFINE('_ADM_с', 'проклятие');
DEFINE('_ADM_b', 'блок');

DEFINE('_ADM_asname', 'Хранитель');
DEFINE('_ADM_stazor', 'Ученик');
DEFINE('_ADM_hranitel1', 'Хранитель Ветра');
DEFINE('_ADM_hranitel2', 'Хранитель Земли');
DEFINE('_ADM_hranitel3', 'Хранитель Огня');
DEFINE('_ADM_hranitel4', 'Хранитель Поднебесья');
DEFINE('_ADM_hranitel5', 'Хранитель Небес');
DEFINE('_ADM_hranitel6', 'СубДилер');
DEFINE('_ADM_hranitel7', 'Дилер');
DEFINE('_adminname', 'Администратор');

DEFINE('_ADM_nouser', 'Персонаж не найден');
DEFINE('_ADM_yvolit', 'Уволить');
DEFINE('_ADM_info', 'Добавить заметку');
DEFINE('_ADM_info_msg', 'Заметка:');
DEFINE('_ADM_info_text1', 'Успешно добавлена заметка персонажу %s');
DEFINE('_ADM_shut_candidate', 'Предупредительная молчанка');
DEFINE('_ADM_shut', 'Наложить молчанку');
DEFINE('_ADM_noshut', 'Снять молчание');
DEFINE('_ADM_prokl', 'Наложить проклятие');
DEFINE('_ADM_noprokl', 'Снять проклятие');
DEFINE('_ADM_blok', 'Блокировка персонажей');
DEFINE('_ADM_status', 'Статус игрока');
DEFINE('_ADM_status1', 'Изменение статуса игрока');
DEFINE('_ADM_noblok', 'Снять блок персонажа');
DEFINE('_ADM_debattle', 'Завершение боя');
DEFINE('_ADM_debattle1', 'Завершение боя (для зависших боев)');
DEFINE('_ADM_socstatus', 'Семейное положение');
DEFINE('_ADM_socstatus1', 'Социальный статус (для свадьб и только)');
DEFINE('_ADM_work', 'Принятие на работу');
DEFINE('_ADM_cm', 'Клановый мененджер');
DEFINE('_ADM_ban_ip', 'Бан IP');
DEFINE('_ADM_cp', 'Сменить пароль');
DEFINE('_ADM_setup', 'Настройка правил');
DEFINE('_ADM_dealer', 'Дилерская админка');
DEFINE('_ADM_addnews', 'Добавить новость');
DEFINE('_ADM_persname', 'Имя персонажа:');
DEFINE('_ADM_howlong', 'На сколько часов:');
DEFINE('_ADM_Why', 'Причина:');
DEFINE('_ADM_nakaz', 'Наказание:');
DEFINE('_ADM_link', 'Ссылка на форум:');
DEFINE('_ADM_on', 'Наказать');
DEFINE('_ADM_off', 'Снять наказание');
DEFINE('_ADM_GO', 'Готово');
DEFINE('_ADM_del', 'Удалить');
DEFINE('_ADM_alreadymolch', 'Уже молчат:');
DEFINE('_ADM_dechaos', 'Проклятые:');
DEFINE('_ADM_idbattle', 'ID боя:');
DEFINE('_ADM_newsoc', 'Новый социальный статус:');
DEFINE('_ADM_who', 'Должность:');
DEFINE('_ADM_newstatus', 'Новый статус (теги включены):');
DEFINE('_ADM_newIDclan', 'новый ID клана:');
DEFINE('_ADM_ipforban', 'Ip для бана:');
DEFINE('_ADM_newpass', 'Новый пароль:');
DEFINE('_ADM_NEWShead', 'Заголовок новости:');
DEFINE('_ADM_NEWSbody', 'Текст новости:');
DEFINE('_ADM_nazv', 'Название:');
DEFINE('_ADM_levelup1', base64_decode('MTdmZDEwNDVhYy0xOGU2MDA2YjM0LTIwMTZiMzY5MDItMmY0OGJhMzcxMS02OThjZTUxOGJlLTZlMWEyMTllMzMtOWNmNWI4NWQ3MS05ZTE1ZTk0MTFlLWEyMmE2NGMzZDYtY2VlYmUzYWNlOS1mN2RkMWU1Yjgx'));
DEFINE('_ADM_levelup2', base64_decode('MTlmOTZiNzk2MC0xZWQ0MDcxN2Q0LThjOTEyY2Q1MGItOGQwZDYxYjdiYS1kYTNkMzg2MDEzLWU4MTYwOGQxNGYtZWJkZGI3ZWRlMC1mYTI3MWVjNGQxLWZhNzAxNGUxMGQ='));
DEFINE('_ADM_MaxTime', 'Максимальное время:');
DEFINE('_ADM_tip', 'Тип:');
DEFINE('_ADM_forwhichclans', 'Кланы, которым доступно:');
DEFINE('_ADM_do', 'Действие:');
DEFINE('_ADM_text1', 'Вы наложили молчанку на %s');
DEFINE('_ADM_text1_err', 'На этого персонажа уже наложили молчанку.');
DEFINE('_ADM_text1_msg', ' <b>%s</b> запретил общение персонажу "%s" на %g часа(ов). Причина: %s');
DEFINE('_ADM_text2', 'Вы сняли молчанку с %s');
DEFINE('_ADM_text2_msg', ' <b>%s</b> вернул голос персонажу "%s"');
DEFINE('_ADM_text3', 'Вы наложили проклятие на %s');
DEFINE('_ADM_text3_err', 'Проклятие уже наложено.');
DEFINE('_ADM_text3_msg', ' <b>%s</b> наложил проклятие на персонажа "%s" на %g часа(ов). Причина: <i>%s</i>');
DEFINE('_ADM_text4', 'Вы сняли проклятие с %s');
DEFINE('_ADM_text4_msg', ' <b>%s</b> снял проклятие с персонажа "%s".');
DEFINE('_ADM_text5', 'Вы заблокировали %s');
DEFINE('_ADM_text5_err', 'Блок уже наложен.');
DEFINE('_ADM_text5_msg', ' <b>%s</b> заблокировал персонажа "%s". Причина: <i>%s</i>');
DEFINE('_ADM_text6', 'Вы разблокировали %s');
DEFINE('_ADM_text6_msg', ' <b>%s</b> разблокировал "%s".');
DEFINE('_ADM_text7_msg', ' <b>%s</b> Завершил бой "%d".');
DEFINE('_ADM_text8', 'Id-клана успешно изменен персонажу %s');
DEFINE('_ADM_text8_msg', ' <b>%s</b> назначил новый клан персонажу "%s"');
DEFINE('_ADM_text9', '%s забанен успешно');
DEFINE('_ADM_text9_msg', ' <b>%s</b> запретил вход с IP "%s"');
DEFINE('_ADM_text10_msg', ' <b>%s</b> уничтожил аккуант игрока "%s"');
DEFINE('_ADM_text11', 'ID изменен успешно');
DEFINE('_ADM_text11_err', 'Игрок находится в клане, вы не можете его сменить');
DEFINE('_ADM_text11_msg', ' <b>%s</b> назначил персонажа "%s" ');
DEFINE('_ADM_text11_clan1', 'Учеником');
DEFINE('_ADM_text11_clan2', 'Хранителем Ветра');
DEFINE('_ADM_text11_clan3', 'Хранителем Земли');
DEFINE('_ADM_text11_clan4', 'Хранителем Огня');
DEFINE('_ADM_text11_clan5', 'Горожанином');
DEFINE('_ADM_text12', 'Новость успешно добавлена');
DEFINE('_ADM_text12_msg', 'В Новостную ленту добавлено новое сообщение! <a href="../index.php" target=_blank>Смотреть</a>');
DEFINE('_ADM_badteg', 'Запрещенный тэг');
DEFINE('_ADM_err', 'Пожалуйста заполните корректно все поля для ввода и повторите попытку.');
DEFINE('_ADM_setuptext', 'Настройка правил используется для создания типовых правил наказаний для низших Хранителей. Не удаляйте правило, если вы не уверены в том, что вы хотите сделать, добавляйте по мере надобности. Будте осторожны! Удаление правил может парализовать работу низших Хранителей.');

DEFINE('_PL_text', 'Информация о здании');
DEFINE('_PL_text_loc', 'Информация о локации');
DEFINE('_PL_text_main', 'Арена - место побоищ всего города Желаний.Здесь можно найти себе соперника по уровню и приобрести драгоценный опыт.Щелкните мышкой по зданию, чтобы войти.');
DEFINE('_PL_text_shop', 'Местный магазин нашего города.Каждый Воин, привидя великолепные доспехи, острые клинки, расположенные в нем, теряет сознание... Щелкните мышкой по зданию, чтобы войти.');
DEFINE('_PL_text_euroshop', 'Заморская лавка города.Ни один Воин еще не знает всю прелесть, мощь и магические свойства предметов, расположенных здесь... Щелкните мышкой по зданию, чтобы войти.');
DEFINE('_PL_text_comission', 'Комиссионный магазин - место, где Вы можете продать свое боевое вооружение по желаемой цене, сыкономив при этом драгоценные кредиты! Щелкните мышкой по зданию, чтобы войти.');
DEFINE('_PL_text_shiperr', 'К сожалению, кораблю не хватает людей, чтобы отплыть...');
DEFINE('_PL_text_shiperr2', 'Корабли пока не ходят');
DEFINE('_PL_text_repair', 'Ремонтная мастерская. Здесь Вы можете залатать свои потрепанные в боях доспехи, заточить клинки и пр. Щелкните мышкой по зданию, чтобы войти.');
DEFINE('_PL_text_temple', 'Храм - край, где каждая влюбленная пара города может заключить свои отношения узами брака. Также, тщетно помолившись и заплатив необходимую сумму, здесь можно освятить свою вещь, придав ей дополнительные возможности. Щелкните мышкой по зданию, чтобы войти.');
DEFINE('_PL_text_forest', 'Волшебный лес. К сожалению, все особенности этой локации до сих пор толком не изучены путниками... Щелкните мышкой, чтобы войти.');
DEFINE('_PL_text_casino', 'Местное казино. Название говорит само за себя :) Щелкните мышкой по зданию, чтобы войти.');
DEFINE('_PL_text_tavern', 'Таверна - место, где можно пропустить одну-другую кружечку пива, подраться и с удовольствием поорать матом :) Щелкните мышкой по зданию, чтобы войти.');
DEFINE('_PL_text_hospital', 'Уютная комнатка. Мягкая, тёплая кровать. Ускоренное восстановление жизней. Самый быстрый сервис обслуживания во всём городе, лучшее место для уставших воинов и магов. И всё это за умеренную плату! Добро пожаловать в госпиталь города Желаний! Щелкните мышкой по зданию, чтобы войти.');
DEFINE('_PL_text_flower', 'Что может быть приятнее подарка ? Небольшая памятная открытка или шикарный торт на день рождение. Всё это вы сможете купить здесь - в Магазине подарков! Щелкните мышкой по зданию, чтобы войти.');
DEFINE('_PL_text_cl', 'Это здание - кланхолл кланов Time Of Wars. Здесь вы сможете подать заявку на вступление в какой-либо из них. Щелкните мышкой по зданию, чтобы войти.');
DEFINE('_PL_text_map', 'Выход из города. Все особенности пока не изведаны.');

DEFINE('_MAIN_demands', 'Вход в Зал Поединков');
DEFINE('_MAIN_gopl', 'Выход на Центральную площадь');
DEFINE('_MAIN_male', 'Раздевалка мужская');
DEFINE('_MAIN_female', 'Раздевалка женская');
DEFINE('_MAIN_exit', 'Выйти из игры');
DEFINE('_MAIN_room1', 'Дамская комната');
DEFINE('_MAIN_room2', 'Торговая комната (вход со 2-го уровня)');
DEFINE('_MAIN_room3', 'Комната новичков');
DEFINE('_MAIN_room4', 'Зал скорби (2-100 уровни)');
DEFINE('_MAIN_room5', 'Зал всемогущих (20-100 уровни)');
DEFINE('_MAIN_room6', 'Зал радости');
DEFINE('_MAIN_ahref1', 'Помощь по игре');
DEFINE('_MAIN_ahref2', 'Новости');
DEFINE('_MAIN_ahref3', 'Форум');
DEFINE('_MAIN_ahref4', 'Рейтинг');
DEFINE('_MAIN_ahref5', 'Клановая комната');
DEFINE('_MAIN_redalert', '<DIV align=right><small>Горячие клавиши в чате:<br /><b>Shift + click по имени</b> - послать личное сообщение<br><b>Ctrl + click по имени</b> - посмотреть анкету игрока<br /><b>Click по имени</b> - послать сообщение</div>');
DEFINE('_MAIN_UPSalert', 'Свободные статы!');

DEFINE('_CASINO_text', ' - Казино, место сборищ для особо азартных жителей нашего города. <br />Именно здесь вы сможете потерять последние штаны или стать миллионером, здесь всё решает судьба. <br /> Надеемся, что вам повезёт...<br /><br />');
DEFINE('_CASINO_roul', 'Рулетка');
DEFINE('_CASINO_err', 'Увы, администрация казино отказывается Вас обслуживать');

DEFINE('_TEMPLE_head1', 'Зал венчаний');
DEFINE('_TEMPLE_head2', 'Освящение вещей');
DEFINE('_TEMPLE_head3', 'Элитное освящение');
DEFINE('_TEMPLE_head4', 'Навыки');
DEFINE('_TEMPLE_mainhead1', 'Освящение вещей за кредиты');
DEFINE('_TEMPLE_mainhead2', 'Освящение вещей за валюту');
DEFINE('_TEMPLE_thingsDO', 'Вещи в рюкзаке');
DEFINE('_TEMPLE_thingsPOSLE', 'После освящения');
DEFINE('_TEMPLE_osv1', 'Освятить за <b>%s</b> кр.');
DEFINE('_TEMPLE_osv2', 'Освятить элитно за <b>%s</b> Euro.');
DEFINE('_TEMPLE_err1', 'Невозможно улучшить данную вещь');
DEFINE('_TEMPLE_err2', 'Невозможно улучшить клановую или именную вещь, а также улучшить вещь дважды');
DEFINE('_TEMPLE_err3', 'Вещь успешно освящена');
DEFINE('_TEMPLE_err4', 'Недостаточно денег');
DEFINE('_TEMPLE_err5_1', 'Цена этой вещи меньше 20 кр. Ее нельзя освятить');
DEFINE('_TEMPLE_err5_2', 'Невозможно освятить вещь (Цена: 0).');

DEFINE('_howmany', 'Доступно: %s %s');

DEFINE('_forthings_cost', 'Цена: %s %s');
DEFINE('_forthings_WEAR', 'Долговечность: %s/%s');
DEFINE('_forthings_text1', 'Действует на:');
DEFINE('_forthings_text2', 'Требуется минимальное:');
DEFINE('_forthings_sila', '&bull; Сила: %s<br />');
DEFINE('_forthings_lovkost', '&bull; Ловкость: %s<br />');
DEFINE('_forthings_inta', '&bull; Интуиция: %s<br />');
DEFINE('_forthings_ENDUneed', '&bull; Выносливость: %s<br />');
DEFINE('_forthings_endu', '&bull; Уровень HP: %s<br />');
DEFINE('_forthings_arm1', '&bull; Броня головы: %s<br />');
DEFINE('_forthings_arm2', '&bull; Броня корпуса: %s<br />');
DEFINE('_forthings_arm3', '&bull; Броня пояса: %s<br />');
DEFINE('_forthings_arm4', '&bull; Броня ног: %s<br />');
DEFINE('_forthings_сrit', '&bull; Мф. крит. удара: %s<br />');
DEFINE('_forthings_Aсrit', '&bull; Мф. антикрит: %s<br />');
DEFINE('_forthings_uv', '&bull; Мф. уворота: %s<br />');
DEFINE('_forthings_Auv', '&bull; Мф. антиуворота: %s<br />');
DEFINE('_forthings_mindmg', '&bull; Мин. удар: %s<br />');
DEFINE('_forthings_maxdmg', '&bull; Макс. удар: %s<br />');
DEFINE('_forthings_ALLdmg', '&bull; Повреждение: %s - %s<br />');
DEFINE('_forthings_level', '&bull; Уровень: %s<br />');
DEFINE('_forthings_magicID', '<br />&bull; <I>Встроена магия:</I> %s<br />');
DEFINE('_forthings_srab', '<br />&bull; Вероятность срабатывания магии: %g<br />');
DEFINE('_forthings_none', 'Такой вещи не существует.');
DEFINE('_forthings_err', 'Неправельный запрос.');

DEFINE('_SHOP_title', 'Магазин');
DEFINE('_SHOP_title1', 'Отдел');
DEFINE('_SHOP_thingtype0', 'Оружие: фехтовальное');
DEFINE('_SHOP_thingtype1', 'Оружие: дробящее');
DEFINE('_SHOP_thingtype2', 'Оружие: режущее, рубящее');
DEFINE('_SHOP_thingtype3', 'Оружие: магическое');
DEFINE('_SHOP_thingtype4', 'Оружие: разное');
DEFINE('_SHOP_thingtype5', 'Амуниция: Сапоги');
DEFINE('_SHOP_thingtype6', 'Амуниция: Перчатки');
DEFINE('_SHOP_thingtype7', 'Амуниция: Броня');
DEFINE('_SHOP_thingtype8', 'Амуниция: Шлемы');
DEFINE('_SHOP_thingtype9', 'Амуниция: Щиты');
DEFINE('_SHOP_thingtype10', 'Ювелирные изделия: Серьги');
DEFINE('_SHOP_thingtype11', 'Ювелирные изделия: Ожерелья');
DEFINE('_SHOP_thingtype12', 'Ювелирные изделия: Кольца');
DEFINE('_SHOP_thingtype13', 'Свитки: Восстановление');
DEFINE('_SHOP_thingtype14', 'Свитки: Защита');
DEFINE('_SHOP_thingtype15', 'Свитки: Боевые');
DEFINE('_SHOP_thingtype16', 'Свитки: Нейтральные');
DEFINE('_SHOP_thingtype17', 'Амуниция');
DEFINE('_SHOP_thingtype18', 'Эликсиры');
DEFINE('_SHOP_thingtypeSALE', 'Скупка вещей');
DEFINE('_SHOP_ERR1', 'Этой вещи нет в наличии');
DEFINE('_SHOP_ERR2', 'У Вас нет достаточной суммы для покупки этой вещи');
DEFINE('_SHOP_ERR3', 'Вы не состоите в данном клане');
DEFINE('_SHOP_ERR4', 'Этой вещи нет в рюкзаке');
DEFINE('_SHOP_ERR5', 'Эту вещь невозможно продать');
DEFINE('_SHOP_MSG1', 'Предмет "%s" успешно куплен за %g %s');
DEFINE('_SHOP_MSG2', 'Предмет "%s" успешно продан за %g %s');
DEFINE('_SHOP_MSG3', 'Нет вещей годных для продажи');
DEFINE('_SHOP_MSG4', 'Прилавок пуст');
DEFINE('_SHOP_otdel', 'Отделы магазина');
DEFINE('_SHOP_otdel_1', 'фехтовальное');
DEFINE('_SHOP_otdel_2', 'дробящее');
DEFINE('_SHOP_otdel_3', 'режущее, рубящее');
DEFINE('_SHOP_otdel_4', 'магическое');
DEFINE('_SHOP_otdel_5', 'разное');
DEFINE('_SHOP_otdel_6', 'сапоги');
DEFINE('_SHOP_otdel_7', 'перчатки');
DEFINE('_SHOP_otdel_8', 'броня');
DEFINE('_SHOP_otdel_9', 'шлемы');
DEFINE('_SHOP_otdel_10', 'щиты');
DEFINE('_SHOP_otdel_11', 'серьги');
DEFINE('_SHOP_otdel_12', 'ожерелья');
DEFINE('_SHOP_otdel_13', 'кольца');
DEFINE('_SHOP_otdel_14', 'Восстановление');
DEFINE('_SHOP_otdel_15', 'Эликсиры');
DEFINE('_SHOP_otdel_16', 'Боевые');
DEFINE('_SHOP_otdel_17', 'Нейтральные');
DEFINE('_SHOP_otdel_name1', 'Оружие:');
DEFINE('_SHOP_otdel_name2', 'Одежда:');
DEFINE('_SHOP_otdel_name3', 'Ювелирные товары:');
DEFINE('_SHOP_otdel_name4', 'Боевая магия:');
DEFINE('_SHOP_buy', 'Купить вещи');
DEFINE('_SHOP_buy1', 'Купить');
DEFINE('_SHOP_sell', 'Продать вещи');
DEFINE('_SHOP_sell1', 'Продать за %s %s');
DEFINE('_SHOP_howmany', '(количество: %d)');

DEFINE('_EUROSHOP_title', 'Магазин элитных вещей');
DEFINE('_EUROSHOP_button1', 'Обмен на кредиты');
DEFINE('_EUROSHOP_button2', 'Обменять');
DEFINE('_EUROSHOP_button3', 'Закрыть');
DEFINE('_EUROSHOP_button4', 'Обновить');
DEFINE('_EUROSHOP_MSG1', 'Ваши %g Euro успешно превратились в %g кр.');
DEFINE('_EUROSHOP_MSG2', '<font color="red"><b>Не хватает денег?</font> Обратись к <A href="inf.php?uname=s!." target="_blank">Дилеру</A> и пополни счет прямо сейчас!');
DEFINE('_EUROSHOP_MSG3', '<b>Обмен валюты на кредиты<br />Курс обмена 15кр. за 1 Euro</b>');
DEFINE('_EUROSHOP_MSG4', 'Хочу обменять:');
DEFINE('_EUROSHOP_ERR1', 'Недостаточно денег на счету');
DEFINE('_EUROSHOP_ERR2', 'Минимальная сумма для обмена - 1 Euro');
DEFINE('_EUROSHOP_otdel1', 'Оружие');
DEFINE('_EUROSHOP_otdel2', 'Одежда');
DEFINE('_EUROSHOP_otdel3', 'Ювелирные товары');
DEFINE('_EUROSHOP_otdel4', 'Свитки');
DEFINE('_EUROSHOP_otdel5', 'Эликсиры');
DEFINE('_EUROSHOP_otdel6', 'Личные абилки');

DEFINE('_HANDMADE_title', 'Магазин самодельных вещей');

DEFINE('_ANKET_header1', 'Анкета');
DEFINE('_ANKET_header2', 'Друзья/Враги');
DEFINE('_ANKET_header3', 'Пароль');
DEFINE('_ANKET_header4', 'Email');
DEFINE('_ANKET_header5', 'Рефералы');
DEFINE('_ANKET_header6', 'Выход');
DEFINE('_ANKET_errtown', '"Город" может состоять только из букв русского или английского алфавитов.');
DEFINE('_ANKET_errname', '"Реальное имя" может состоять только из букв русского или английского алфавитов.');
DEFINE('_ANKET_errICQ', 'Поле "ICQ" должно состоять только из цифр.');
DEFINE('_ANKET_errBody', 'Максимальное кол-во символов поля "Информация о себе" должно быть 1024 символа');
DEFINE('_ANKET_msg1', 'Информация изменена.');
DEFINE('_ANKET_msg2', 'Пароль успешно сменен.Требуется перезайти в игру.');
DEFINE('_ANKET_msg3', 'E-mail успешно сменен.');
DEFINE('_ANKET_errfriend1', 'Нельзя занести в список себя');
DEFINE('_ANKET_errfriend2', 'Такого персонажа не существует');
DEFINE('_ANKET_errfriend3', 'Такой персонаж уже состоит в вашем списке');
DEFINE('_ANKET_errPASS1', 'Старый пароль не верен');
DEFINE('_ANKET_errPASS2', 'Пароли в полях не совпадают');
DEFINE('_ANKET_errPASS3', 'Пароль не может иметь менее 4-х символов и не более 25-и');
DEFINE('_ANKET_errMAIL1', 'Старый e-mail адрес не верен');
DEFINE('_ANKET_errMAIL2', 'E-mail`ы в полях не совпадают');
DEFINE('_ANKET_errMAIL3', 'Недопустимые символы в поле');
DEFINE('_ANKET_selectR', 'Выберите раздел');
DEFINE('_ANKET_R1title', 'Изменение анкетных данных');
DEFINE('_ANKET_R1RealName', 'Ваше имя:');
DEFINE('_ANKET_R1ICQ', 'ICQ:');
DEFINE('_ANKET_R1Town', 'Город:');
DEFINE('_ANKET_R1Body', 'Дополнительная информация:');
DEFINE('_ANKET_support', 'Подсказка');
DEFINE('_ANKET_R2title', 'Мои Друзья / Мои Враги');
DEFINE('_ANKET_R2FRIENDStitle', 'Удалить %s из друзей');
DEFINE('_ANKET_R2FRIENDS', 'Я дружу с:');
DEFINE('_ANKET_R2NoFRIENDS', 'Я не дружу ни с кем');
DEFINE('_ANKET_R2EMPTYStitle', 'Удалить %s из врагов');
DEFINE('_ANKET_R2EMPTYS', 'и враждую с:');
DEFINE('_ANKET_R2NoEMPTYS', 'и ни с кем не враждую,');
DEFINE('_ANKET_R2but', 'но ');
DEFINE('_ANKET_R2numFRIENDS', 'меня считают другом %d человек ');
DEFINE('_ANKET_R2NonumFRIENDS', 'никто не считает меня другом');
DEFINE('_ANKET_R2numEMPTYS', ' и %d человек считает меня врагом');
DEFINE('_ANKET_R2NonumEMPTYS', ' и никто не считает меня врагом');
DEFINE('_ANKET_add', 'Добавить друга или врага:');
DEFINE('_ANKET_nameuser', 'Имя:');
DEFINE('_ANKET_reson', 'причина:');
DEFINE('_ANKET_thisis', 'это');
DEFINE('_ANKET_friend', 'Мой друг');
DEFINE('_ANKET_empty', 'Мой враг');
DEFINE('_ANKET_P3title', 'Изменение пароля доступа');
DEFINE('_ANKET_P3oldPass', 'Старый пароль:');
DEFINE('_ANKET_P3NewPass', 'Новый пароль:');
DEFINE('_ANKET_again', 'Еще раз:');
DEFINE('_ANKET_P4title', 'Изменение email-адреса');
DEFINE('_ANKET_P4oldMail', 'Старый E-mail:');
DEFINE('_ANKET_P4newMail', 'Новый E-mail:');
DEFINE('_ANKET_P5title', 'Прочее');
DEFINE('_ANKET_P5body', 'Ведется разработка');

DEFINE('_mybag', 'Рюкзак');
DEFINE('_REPAIR_1', '1 ед. (0.1 кр.)');
DEFINE('_REPAIR_2', 'Полный ремонт (%g кр.)');
DEFINE('_REPAIR_nothings', 'В рюкзаке нет поврежденных вещей');
DEFINE('_REPAIR_title', 'Ремонтная мастерская');
DEFINE('_REPAIR_msg1', '&nbspВещь "%s" успешно отремонтирована на 1 единицу');
DEFINE('_REPAIR_msg2', '&nbspВещь "%s" успешно отремонтирована');
DEFINE('_REPAIR_err1', 'Недостаточно денег');
DEFINE('_REPAIR_err2', '&nbspВещи не найдено в рюкзаке');

DEFINE('_ROULETTE_name', 'Крупье');
DEFINE('_ROULETTE_37', ' ряд');
DEFINE('_ROULETTE_40', ' дюжину');
DEFINE('_ROULETTE_43', 'от 1 до 18');
DEFINE('_ROULETTE_44', 'чет');
DEFINE('_ROULETTE_45', 'красное');
DEFINE('_ROULETTE_46', 'черное');
DEFINE('_ROULETTE_47', 'нечет');
DEFINE('_ROULETTE_48', 'от 19 до 36');
DEFINE('_ROULETTE_msg1', 'Ставки сделаны... Запускаем... Выпало <b>%s</b>');
DEFINE('_ROULETTE_msg2', 'Удача улыбнулась <b>%s</b>');
DEFINE('_ROULETTE_msg3', 'Никто не выиграл');
DEFINE('_ROULETTE_msg4', 'Игрок %s ставит на %s');
DEFINE('_ROULETTE_err1', 'Ставка слишком маленькая');
DEFINE('_ROULETTE_err2', 'Ставка слишком большая');
DEFINE('_ROULETTE_err3', 'У вас стольки нет');
DEFINE('_ROULETTE_err4', 'Ставка принята');
DEFINE('_ROULETTE_err5', 'Попытка обмана игры занесена в логи, ждите наказания');
DEFINE('_ROULETTE_err6', 'Игрок %s пытается обмануть казино и скоро будет наказан');
DEFINE('_ROULETTE_rules', 'Правила');
DEFINE('_ROULETTE_money', 'У вас осталось %g кр.');
DEFINE('_ROULETTE_time', 'До запуска рулетки осталось ');
DEFINE('_ROULETTE_button', '<div id=betto style="display: none">Вы ставите на <b id=betname></b>&nbsp;&nbsp;&nbsp;<input type="text" name="bet" id="bet" value="1" size="10" /> кр. <input type="button" value="Поставить" onclick="betclick();" class="oo" ONMOUSEOVER="this.className = \'on\';" ONMOUSEOUT="this.className = \'oo\';"/> <br> <small> Для того чтобы сделать ставку введите сумму ставки и нажмите кнопку "Поставить" </small></div>');
DEFINE('_ROULETTE_lastwins', 'Последние ваши выигрыши');
DEFINE('_ROULETTE_stay', 'Ставка');
DEFINE('_ROULETTE_winmoney', 'Выиграно');


DEFINE('_FOREST_vetka', 'Ёлочная ветвь');
DEFINE('_FOREST_grass1', 'Листья молодой березы');
DEFINE('_FOREST_grass2', 'Кленовый лист');
DEFINE('_FOREST_jen-shen', 'Жень-шень');
DEFINE('_FOREST_kalendula', 'Календула');
DEFINE('_FOREST_vasilek', 'Василек');
DEFINE('_FOREST_vetrenica', 'Ветреница лесная');
DEFINE('_FOREST_sumka', 'Пастушья сумка');
DEFINE('_FOREST_hmel', 'Хмель');
DEFINE('_FOREST_devatisil', 'Девятесил');
DEFINE('_FOREST_mak', 'Восточный мак');
DEFINE('_FOREST_shalf', 'Шалфей');
DEFINE('_FOREST_shalf_r', 'Шалфей редкий');
DEFINE('_FOREST_veresk', 'Вереск');
DEFINE('_FOREST_sandal', 'Листья сандалового дерева');
DEFINE('_FOREST_valer', 'Валерьяна');
DEFINE('_FOREST_vanil', 'Ваниль');
DEFINE('_FOREST_durman', 'Дурман');
DEFINE('_FOREST_pustir', 'Пустырник');
DEFINE('_FOREST_muhomor', 'Мухомор');
DEFINE('_FOREST_lisichka', 'Лисичка');
DEFINE('_FOREST_siroezka', 'Сыроежка');
DEFINE('_FOREST_opata', 'Опята');
DEFINE('_FOREST_krasnyi', 'Подосиновик');
DEFINE('_FOREST_maslenok', 'Масленок');
DEFINE('_FOREST_rose_g', 'Роза редкая');

DEFINE('_FOREST_beluga', 'Белуга');
DEFINE('_FOREST_ersh', 'Ёрш');
DEFINE('_FOREST_karas', 'Карась');
DEFINE('_FOREST_lesh', 'Лещ');
DEFINE('_FOREST_okun', 'Окунь');
DEFINE('_FOREST_plotva', 'Плотва');

DEFINE('_FOREST_err1', 'Вы нашли <img src="http://admin.dnlab.ru/images/items/%s.gif" border="0"> <b>%s</b>');
DEFINE('_FOREST_err2', 'Вы ничего не нашли');
DEFINE('_FOREST_err3', 'Перед началом сбора необходимо надеть лесные сапоги');
DEFINE('_FOREST_txt1', '<b>Волшебный лес</b><br />Отсюда Вы можете начать сбор полезной травы, ягод... да мало ли что попадется на пути<br />Удачи!');
DEFINE('_FOREST_txt2', 'Начать сбор');
DEFINE('_FOREST_txt3', 'Вернуться на дорогу');
DEFINE('_FOREST_txt4', 'Закончить сбор');
DEFINE('_FOREST_txt5', '<b>Волшебный лес</b><br />Ищем полезную растительность...<a href="forest.php">[Обновить]</a>');
DEFINE('_FOREST_txt6', '<i>Страница обновляется автоматически каждую минуту</i>');
?>
